### ISSUE TITLE
Gnome 3.32 Support

### ISSUE THREAD

**Issue by edrose** [gnome-pomodoro/gnome-pomodoro#416] opened 2019-03-18 09:53 UTC
Unfortunately Gnome 3.32 breaks this extension. From what I understand, Gnome 3.32 introduced a new version of GJS which has broken many extensions since it's release. In it's  current state, Pomodoro Timer doesn't actually build. The error message is:

```
make[3]: Entering directory '/home/ed/Downloads/gnome-shell-pomodoro/gnome-pomodoro-0.14.0/lib'
  VALAC    libgnome_pomodoro_la_vala.stamp
application.vala:149.43-149.71: error: Assignment: Cannot convert from `GLib.List<Gtk.Window>' to `GLib.List<weak Gtk.Window>?'
            unowned List<weak Gtk.Window> windows = this.get_windows ();
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
application.vala:151.20-151.26: error: The name `windows' does not exist in the context of `Pomodoro.Application.get_last_focused_window'
            return windows != null
                   ^^^^^^^
application.vala:152.23-152.29: error: The name `windows' does not exist in the context of `Pomodoro.Application.get_last_focused_window'
                    ? windows.first ().data
                      ^^^^^^^
application.vala:69.9-69.30: error: struct `Pomodoro.Application.Options' cannot be empty
        private struct Options
        ^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 4 error(s), 0 warning(s)
```

Hopefully Relevant information about my system:

* Arch Linux
* Gnome Shell 1:3.32.0+16+g1341d5557-1 (Arch package version)
* GJS 1.56.0
* glib2 2.60.0-1

**Comment by snizovtsev** [comment] 2019-03-18 13:49
I think it's a duplicate of #402

**Comment by snizovtsev** [comment] 2019-03-18 14:32
I've fixed build errors in #417 but still have no indicator and notifications:
```
мар 18 17:23:49 winnie gnome-shell[1087]: JS ERROR: Exception in callback for signal: state-changed: TypeError: this._construct is not a function
                                             newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
                                             _notifyPomodoroStart@/usr/share/gnome-shell/extensions/pomodoro@arun.codito.in/extension.js:243:33
                                             wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                             _updateNotification@/usr/share/gnome-shell/extensions/pomodoro@arun.codito.in/extension.js:318:21
                                             wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                             _update@/usr/share/gnome-shell/extensions/pomodoro@arun.codito.in/extension.js:372:13
                                             wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                             _onTimerStateChanged@/usr/share/gnome-shell/extensions/pomodoro@arun.codito.in/extension.js:219:9
                                             wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                             _emit@resource:///org/gnome/gjs/modules/signals.js:142:27
                                             _onPropertiesChanged@/usr/share/gnome-shell/extensions/pomodoro@arun.codito.in/timer.js:105:13
                                             wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
```

**Comment by BrainBlasted** [comment] 2019-03-19 08:52
gnome-pomodoro needs to be updated to use ES6 classes instead of Lang.Class. See https://gitlab.gnome.org/GNOME/gnome-weather/commit/6977789e3d9240d3082a3141897c74b543dfd423 for details

**Comment by edrose** [comment] 2019-03-19 10:39
Sorry for the duplicate issue. I naively assumed that the build errors were caused by the 3.32 update and therefore didn't look back through the comments more then a couple of days.

Cheers @BrainBlasted for providing proper info on my issue.

**Comment by codito** [comment] 2019-03-23 12:00
Merged patch by @demokritos. No issues so far on my local testing. Can you please try out latest master?

**Comment by 04a391c1b7aa** [comment] 2019-03-24 12:08
I can confirm it. Here, #417 and #418 fixed the issues for gnome 3.32. Big thanks to the contributors!

**Comment by obilodeau** [comment] 2019-04-02 15:45
@codito are you planning to cut a release? This would prevent extra work downstream.

**Comment by codito** [comment] 2019-04-02 16:19
@obilodeau I've reached out to @kamilprusko to help with release for gnome 3.32.

**Comment by codito** [comment] 2019-04-07 04:57
0.15.1 is out with gnome 3.32 support!
https://github.com/codito/gnome-pomodoro/releases/tag/0.15.1

**Comment by stouf** [comment] 2019-04-18 02:01
Does the extension now work for everybody? While the application itself works for me, the extension doesn't 😕
I have a warning sign on the extension entry in Gnome Tweaks:
![Screenshot from 2019-04-18 10-57-33](https://user-images.githubusercontent.com/2033517/56331825-de279400-61c8-11e9-810b-537fc68fd8f7.png)
When I hover it with the mouse, it tells it failed to load the extension.
Also, when I open the application, I get an error message in the notification area:

> **Failed to enabled extension**
> SyntaxError: expected expression, got '<'

The application works perfectly fine though.
Is there a way for me to provide more information that may help debugging the issue? Logs maybe?

**Comment by octoquad** [comment] 2019-04-19 04:38
I've just built the extension from the gnome-3.32 branch under Ubuntu Disco Dingo (19.04) and the extension seems to working correctly.

![image](https://user-images.githubusercontent.com/1165755/56405441-85113c00-626c-11e9-9a90-acef76a858c1.png)

I see that the https://gnomepomodoro.org/ currently does not have instructions for Disco Dingo. The instructions for Cosmic Cuttlefish work though, just the branch name needs to be changed to gnome-3.32.

Thanks

**Comment by dmulder** [comment] 2019-05-14 16:12
> Does the extension now work for everybody? While the application itself works for me, the extension doesn't 
> I have a warning sign on the extension entry in Gnome Tweaks:
> ![Screenshot from 2019-04-18 10-57-33](https://user-images.githubusercontent.com/2033517/56331825-de279400-61c8-11e9-810b-537fc68fd8f7.png)
> When I hover it with the mouse, it tells it failed to load the extension.
> Also, when I open the application, I get an error message in the notification area:
> 
> > **Failed to enabled extension**
> > SyntaxError: expected expression, got '<'
> 
> The application works perfectly fine though.
> Is there a way for me to provide more information that may help debugging the issue? Logs maybe?

I see this same issue in openSUSE with gnome 3.32. Pomodoro builds/loads, but I get that error "SyntaxError: expected expression, got '<'" on load (and the extension doesn't work). If I open pomodoro, I get that message in a popup, and the timer works, but stats don't work.

**Comment by dmulder** [comment] 2019-05-14 16:30
Also, I just tried build from the 3.32 source branch, and I still see the same thing.

**Comment by dmulder** [comment] 2019-05-14 16:38
> I've just built the extension from the gnome-3.32 branch under Ubuntu Disco Dingo (19.04) and the extension seems to working correctly.
> 
I wonder if this issue only happens on new installs? Maybe some setup issue? I have never run pomodoro on this machine before.

**Comment by octoquad** [comment] 2019-05-14 17:08
> > I've just built the extension from the gnome-3.32 branch under Ubuntu Disco Dingo (19.04) and the extension seems to working correctly.
> 
> I wonder if this issue only happens on new installs? Maybe some setup issue? I have never run pomodoro on this machine before.

I upgraded from 18.10 which had gnome-shell-extension-pomodoro installed, but it got removed on upgrade. I decided to then compile from source and I haven't had an issue since my last post here, and stats are working as well. I'm not sure if openSUSE ships this as a package. I assume that if openSUSE does ship one, that you removed it first before trying to run the compiled one?

**Comment by ramonsuarez** [comment] 2019-06-17 09:24
> 0.15.1 is out with gnome 3.32 support!
> https://github.com/codito/gnome-pomodoro/releases/tag/0.15.1

Gnome-Pomodoro compiled and installed with this release, but the shell extension does not work and the icon is not displayed.

**Comment by arcooke** [comment] 2019-08-05 02:47
Website still does not display an option for 3.32

![image](https://user-images.githubusercontent.com/6278400/62435327-54f98600-b701-11e9-924f-8b3e94c8df45.png)

**Comment by aadilayub** [comment] 2019-08-09 08:24
The extension is broken for me as well on Fedora 30 (GNOME 3.32.2)

![image](https://user-images.githubusercontent.com/31581044/62765170-f89fb900-baa8-11e9-91f0-0e5ab66b2d94.png)

**Comment by sojusnik** [comment] 2019-08-09 09:54
Make sure that after compiling from source (replace 3.30 with 3.32 in `git clone -b gnome-3.30 …`) the extension lies only in `/usr/share/gnome-shell/extensions/pomodoro@arun.codito.in`. Just follow the [usual instruction](https://i.imgur.com/hheiSUu.png). Worked for me on Ubuntu 19.04.

**Closed** 2024-07-21 09:14 UTC
