### ISSUE TITLE
cant quit break screen on Fedora 34

### ISSUE THREAD

**Issue by fut33v** [gnome-pomodoro/gnome-pomodoro#604] opened 2021-12-14 08:41 UTC
## Issue Summary

When splash screen with break on 5 minutes appears I cant close it with any mouse or keyboard interactions, only killing pomodoro from console mode without gui helps.

## Steps to Reproduce

1. run pomodoro timer for 25 minutes
2. wait for break

**Comment by kamilprusko** [comment] 2021-12-14 17:05
When an app steals focus the modal becomes unresponsive. This was patched partially in 0.19.2 version, but it's still easy to reproduce by playing a video in Totem.

**Comment by obilodeau** [comment] 2022-03-24 19:05
The same happened to me several times today. I thought it was because a full-screen VM was grabbing X input but now I can't reproduce... I'll try the NumLock trick and report back.

**Comment by s4ln1x** [comment] 2022-03-29 21:23
Happened to me today on Fedora 35

**Comment by real-or-random** [comment] 2022-04-18 15:49
> When an app steals focus the modal becomes unresponsive. This was patched partially in 0.19.2 version, but it's still easy to reproduce by playing a video in Totem.

The overlay seems rather fragile, maybe it's a good idea to add an option to disable it? At the moment the only option is to disable the entire extension.

**Comment by janvlug** [comment] 2022-05-12 09:05
Today, when I had to use Microsoft Teams for a video call, the 5 minute break started. I could not escape from the break, so I decided to wait until the break was over (the video call was still working in the dimmed window). However, when the break end was reached, I heard the ping indicating this, but the timer stopped at 1 second before the end. It was a bit fiddling to get out of this break. I think that in the end I used <Ctrl>-L to lock the screen. When I logged in again, the system behaved normally again, and the work pomodoro was started and already counting down. I use Fedora 36.

**Comment by mystilleef** [comment] 2022-05-14 07:32
> Today, when I had to use Microsoft Teams for a video call, the 5 minute break started. I could not escape from the break, so I decided to wait until the break was over (the video call was still working in the dimmed window). However, when the break end was reached, I heard the ping indicating this, but the timer stopped at 1 second before the end. It was a bit fiddling to get out of this break. I think that in the end I used <Ctrl>-L to lock the screen. When I logged in again, the system behaved normally again, and the work pomodoro was started and already counting down. I use Fedora 36.

Same issue here. I notice when video or audio is playing, you cannot escape the break window. I'm also on Fedora 36. Thanks for the lock screen workaround. On some distros, locking the screen is WIN+L, in case CTRL+L doesn't work for some.

**Comment by janvlug** [comment] 2022-05-14 07:51
Soon an updated version will be available in the testing repository for Fedora 36:
`dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2022-bfb43e54c3`

**Comment by mystilleef** [comment] 2022-05-14 18:03
> 

Does it address this issue?

**Comment by janvlug** [comment] 2022-05-15 20:44
> Does it address this issue?

Yes, it seems to fix this bug and https://github.com/gnome-pomodoro/gnome-pomodoro/issues/619.

**Comment by logrusx** [comment] 2022-05-16 06:27
Any custom patches from Fedora's side?

**Comment by mbooth101** [comment] 2022-05-18 09:47
> Any custom patches from Fedora's side?

I added no extra patches downstream, just updated to the latest release 0.21.1

**Comment by gulprun** [comment] 2022-05-20 07:07
Not on Ubuntu?

**Comment by mbooth101** [comment] 2022-05-20 12:23
> Not on Ubuntu?

I only maintain the Fedora package. I'd recommend filing a bug with ubuntu to get the maintainer to update the package there.

**Comment by obilodeau** [comment] 2022-05-31 14:20
0.21.1 didn't fix this bug for me. I'm on arch linux and compiled 0.21.1 myself last Saturday, restarted gnome-shell since.

The lock screen workaround doesn't work.

How can we debug this? I would love to attach to the process when the modal is locked and see the GTK properties. Any pointers to do so appreciated.

**Comment by mzilhao** [comment] 2022-05-31 16:39
I'm also having similar issues with Fedora 36 and 0.21.1. In most cases everything works fine, but there are situations where I can't exit the break screen and have to let clock run down. I haven't quite figured out what triggers this, but it does seem to happen more often whenever sound and/or video is playing.

**Comment by janvlug** [comment] 2022-06-02 09:26
I ran in this issue again when watching YouTube in Firefox in full screen when the 5-minutes break kicked in. `<Esc>` did not work to get out of the break, but the `<Super>-L` trick worked. Using: gnome-pomodoro.x86_64, 1:0.21.1-1.fc36.

**Comment by prahal** [comment] 2022-07-14 20:19
I have made up https://github.com/gnome-pomodoro/gnome-pomodoro/pull/630 to fix my issue. Likely this issue was gnome-shell pre 42 only and matches mine.

**Comment by jvanz** [comment] 2022-08-10 19:01
I also cannot leave the break window on openSUSE Leap  15.4 using wayland and GNOME 41.2

**Comment by taw00** [comment] 2022-08-12 18:10
Sometimes you can leave the break blur-out with keyboard or mouse activity. Sometimes you can't. BUG. The CTRL-ALT-P thing is a non-obvious solution, so ... (user experience BUG or "improvement needed" or "documentation needed" or whatever).

**Comment by taw00** [comment] 2022-08-12 18:19
> UPDATE: to leave the break window I need to press ctrl+alt+p. Which is the shortcut to toggle the timer

Thanks for this. It's a good workaround until @prahal's patch is merged. It's been a month though since he made the pull request, so ... Well, we'll see.

**Comment by jvanz** [comment] 2022-09-23 02:47
I noticed something Today. If I wait 2 seconds, I can leave the break screen moving the mouse.

**Comment by prahal** [comment] 2022-09-23 20:08
My patch has been merged. @jvanz can you test the current git master code?

Also, I am also able to close the break overlay if I wait for a few seconds and press the escape key or the left mouse button. If you do not wait and do any interaction immediately the break overlay is not exited, only if you wait a few seconds then interact. This is unrelated to this issue. I do not know if it is expected or not. You might want to open another issue to sort this out.

I believe this issue could be closed once you confirmed it was the same bug as was fixed in my push request.

**Comment by kamilprusko** [comment] 2022-10-02 12:49
Haven't experienced this issue since applying @upsuper's and @prahal's patches. Closing.

**Closed by kamilprusko** 2022-10-02 12:49 UTC

**Comment by gamma19** [comment] 2023-07-05 19:50
Ctrl+Alt+p then logging out then logging in (in Ubuntu) solved my issue. Thanks.

**Comment by ventolinmx** [comment] 2024-04-22 19:09
For me the Gnome Extension for Pomodoro taskbar icon was causing the time break to block any input. The gnome application from the Snap Store doesn't shows an icon in the taskbar so I installed the extension but this blocks the screen.
